# Sniperkit-Bot
# - Status: analyzed

stages:
  - mirroring
  - routines
  - publish

pages:
  stage: mirroring
  tags:
    - docs
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd -
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

job_mirror:
  stage: mirroring
  only:
    - master
  script:
    - ~/gitsync.sh
  allow_failure: true


simple_tests:
  stage: routines
  tags:
    - ubuntu
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  script:
    - ctest -V -S /work/gltest.cmake
  artifacts:
    paths:
    - build/here
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log    
    expire_in: 12 hrs
    when: always
  retry: 1


release_tests:
  stage: routines
  tags:
    - ubuntu
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  script:
    - ctest -V -DCTEST_BUILD_CONFIGURATION=RelWithDebInfo -S /work/gltest.cmake
  artifacts:
    paths:
    - build/here
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log    
    expire_in: 12 hrs
    when: always
  retry: 1

push_results:
  stage: publish
  tags:
    - ubuntu
    - specdocker
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  dependencies:
    - simple_tests
    - release_tests
  variables:
    GIT_STRATEGY: none
  script:
    - ctest -S /work/upload.cmake
  when: always
  artifacts:
    paths:
    - results.html
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: http://$CDASH_URL/CDash/public/index.php?project=Manticoresearch&filtercount=1&field1=revision&compare1=63&value1=$CI_COMMIT_SHA
  retry: 1




